import Head from "next/head";
import styles from "../styles/Home.module.css";
// import "../styles/style.css"; Cannot do this, should be added in _app.js

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <style jsx>{`
        h2 {
          font-size: 38px;
        }
        h3 {
          font-size: 28px;
        }
      `}</style> */}
      <Head>
        <title>Welcome to Hunting Coder </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload"></Script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="">&lt;HuntingCoder/&gt;</span>
        </h1>
        <div className={styles.heroBanner}>
          <img
            src="/HeroBanner.jpg"
            alt="Hunting Coder"
            width={237}
            height={158}
          />
        </div>
        <p className={styles.description}>
          &quot;A blog for Hunting coders by a hunting coder&quot;
        </p>

        <div className="blogs">
          <h2 className={styles.blogsheading}>Latest Blogs</h2>
          <div className={styles.blogsItems}>
            <h3>How to learn JS in 2023?</h3>
            <p>JavaScript is the language used to desing logic for the web</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className={styles.blogsItems}>
            <h3>How to learn JS in 2023?</h3>
            <p>JavaScript is the language used to desing logic for the web</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className={styles.blogsItems}>
            <h3>How to learn JS in 2023?</h3>
            <p>JavaScript is the language used to desing logic for the web</p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
